### ISSUE TITLE
not compatible with Qgis 3.10

### ISSUE THREAD

**Issue by jeanbaptisteb** [rduivenvoorde/simplesvg#16]
All is in the title!

**Comment by rduivenvoorde** [comment]
It should, can you provide information why it is not? Screendumps, OperatingSystem, Errors, Data you are trying to save as svg etcetc.

You are now asking me "hey it does not work for me, go and see if you can make it not work for you too"... but it is working for me :-)

Also: please provide example data with which it is NOT working, and also note that it is 'Simple' as in: the main goal is to dump spatial data to svg to rework in Inkscape. NOT to create a nice map in QGIS which is then including all styling dumped to svg..

**Comment by jeanbaptisteb** [comment]
Oops, sorry for the brief message, as Qgis throwed me a message saying that this extension wasn't compatible with this version, I assumed it was the case for all people who use this version! 

I copy-pasted all my system information at the end of this message, but in short I use Qgis 3.10.0 (A Coruña), more specifically a French-localized version of QGIS, installed with OSGeo4W. I work on Windows 10, on a 64bits system. 
Other extensions installed: HCMGIS; timemanager; db_manager; MetaSearch; processing. 

Here's what happened:
When I wanted to install it, the extension wasn't listed as available in the repository.
![image](https://user-images.githubusercontent.com/5843240/69244868-1b606400-0ba6-11ea-9bf0-dbee6a8fe318.png)
So I downloaded the zip of the last version on the Qgis website (https://plugins.qgis.org/plugins/simplesvg/), and tried to install it with the "install from zip" option. 
It showed me the following error message: "ModuleNotFoundError: No module name 'simpleSvg"
![image](https://user-images.githubusercontent.com/5843240/69244981-4ea2f300-0ba6-11ea-892c-bb2fd13b0a95.png)
I closed the window, but then I got a message saying that the extension was installed successfully. That was a bit confusing, and I assumed that the installation was successful after all.

I closed QGIS and restarted it. Then, I didn't find where I could access the menu to export to SVG. 
So I checked the list of installed extensions, to see if simpleSVG was correctly installed, and it wasn't. A message was stating that the extension is incompatible with this version of QGIS, because it was conceived to work with QGIS 2.0-2.99.
![image](https://user-images.githubusercontent.com/5843240/69245235-c113d300-0ba6-11ea-9c52-177a1f508a6d.png)

---
System information:

Version de QGIS | 3.10.0-A Coruña | 
Révision du code | 6ffa89eb3e
Compilé avec Qt | 5.11.2 | 
Utilisant Qt | 5.11.2
Compilé avec GDAL/OGR | 3.0.2 | 
Utilisé avec GDAL/OGR | 3.0.2
Compilé avec GEOS | 3.8.0-CAPI-1.13.1 | 
Utilisé avec GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | 
Running against SQLite | 3.29.0
Version du client PostgreSQL | 11.5 | 
Version de SpatiaLite | 4.3.0
Version de QWT | 6.1.3 | 
Version de QScintilla2 | 2.10.8
Compilé avec PROJ | 6.2.1 | 
Fonctionne avec PROJ | Rel. 6.2.1, November 1st, 2019
OS Version | Windows 10 (10.0)
Extensions Python actives | HCMGIS; timemanager; db_manager; MetaSearch; processing

**Comment by rduivenvoorde** [comment]
Ah! That is better... Thanks.
Which reminded me that I fixed SimpleSVG plugin for somebody to work in QGIS 2.18 (which is version 0.0.9, which is NOT compatible with QGIS3), which you tried to download and install.

But I also ported it to (partly) QGIS3, it does not do labels yet, but I could look into that if somebody asks.

I uploaded a 3.0.0 version to plugins.qgis.org now, it will show up within an hour or so (as it is cached), so you should be able to install it via the plugin manager as a normal plugin.

Please remove the 0.0.9 from your QGIS3 install, and install 3.0.0 via plugin manager (if it is available). 
THEN let me know if it worked for you or not :-)

**Comment by jeanbaptisteb** [comment]
It's available in the plugin manager, and the installation works! Thanks :)
